#mainSections = ["blog", "posts"]                                             # Hugo default
mainTypes = ["article", "sitepage", "review"]                                                # YourOnly.One

rssfull = true
jquerycdn = false
websubhubs = ["https://pubsubhubbub.appspot.com/", "https://youronlyone.superfeedr.com/", "https://pubsubhubbub.superfeedr.com/", "https://websubhub.com/hub"]

#googleadsense = "ca-pub-8360283248006398"

favicon_mstilecolor = "#2b5797"

### BGN: Structured Data ###
  siteStartYear = 2023

  description = "Keyboards layouts by YourOnly.One."
  license = ""
  keywords = ["keyboards", "layouts", "designs", "YourOnly.One", "YourOnlyOne"] # Can be overriden per page
  images = ["https://keyboards.youronly.one/favicon/android-chrome-512x512.png"]
  #copyright = ""
### END: Structured Data ###

### BGN: Theme settings
  enableSearch = true

  #[newsletter]
  #  title = "NEWSLETTER_TITLE_HERE"
  #  description = "NEWSLETTER_DESCRIPTION_HERE"

    # Supports buttondown, substack and revue
  #  provider = "buttondown"

    # Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
    # Substack - URL of the newsletter homepage; Example: https://on.substack.com/
    # Revue - Username
  #  path = "https://buttondown.email/api/emails/embed-subscribe/"
### END: Theme settings

### BGN: Other Settings ###
  [semweb]
    org = "yelosan"

    #isni = ""
    #issn = ""
    #acquirelicensepage = "https://im.youronly.one/p/legal-notice/"
    #copyrightnotice = "Copyleft 🄯 CC-BY-SA 4.0 International by JC John Sese Cuneta"
    credittext = "I'M YourOnly.One (https://im.youronly.one/)"
    #datecreated = "2003-12-12"
    isblog = false
    #license = "https://im.youronly.one/p/legal-notice/"
    publisher = "https://yelosan.youronly.one/"
    sameas = [
      "https://facebook.com/101597304949708/",
      "https://facebook.com/yelosanpub/",
      "https://codeberg.org/yelosan",
      "https://gitlab.com/yelosan",
      "https://github.com/yelosan"
    ]

    [[semweb.persons]]
      person = "yuki"
      #id = ""
      #name = ""ᜌᜓᜃᜒ (雪亮 | 스노 | Yuki)"
      #url = ""
      #avatar = ""
      #rel = "noopener external nofollow"

  [verify]
    flattr = "4j1gl5"
    naver = "0212955cb24d6e2c67f92be3c7833cae8a98fa8e"
    wot = "06c7ef6e7986586661ef"
    ocs = "c563648adcfa021a0dfd3d3d8f0be64a"
    followit = "uYZyV7MVARnWg9phNgMQ"

  [analytics]
    counterdev = "youronlyone"
    microanalyticsio = "ZwSg9rf6GA"
    swetrix = "bYdcXUajNvru"
    cfwebanalytics = "07a05e5302d1458da3561ce41791e284"
    microsoftclarity = "63ddi0b99e"
### END: Other Settings ###
