# use /:slug/ for fallback to /:title/ if not set
"/" = "/:slug/"

blog = "/:slug-:year:yearday/"
categories = "/cat/:slug/"
#categories = "/categories/:slug/"
pages = "/:slug/"
posts = "/:slug-:year:yearday/"
#series = "/series/:slug/"
tags = "/tag/:slug/"
#tags = "/tags/:slug/"

#channels = "/channels/:slug/"
#c = "/:sections[1:]/:slug-:year:yearday/"
#kb = "/:sections/:slug-:year:yearday/"
